# plugins/aeon-speak/config.yml
aeon_plugin:
  plugin_name: aeon-speak
  model_path: ./model
  type: text-audio
  command: /say
  parameters: <PROMPT>
  desc: "The voice of Aeon. Use '/say /talk' to open voice chat (to stop say: 'goodbye')"